name: fail2ban

services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "/root/fail2ban/data:/data"
      - "/var/log:/var/log:ro"
      - "/root/nginx/data/logs:/log/npm:ro"
    environment:
      - TZ=Europe/London
      - F2B_LOG_TARGET=STDOUT
      - F2B_LOG_LEVEL=INFO
      - F2B_DB_PURGE_AGE=365d
    restart: always
