services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - proxy

  uptime-kuma:
    image: louislam/uptime-kuma:1
    ports:
      - "127.0.0.1:3001:3001"
    volumes:
      - uptime-kuma:/app/data
    networks:
      - proxy

  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=UTC # optional: set desired timezone
    user: 0:0
    volumes:
      - /var/cache/ntfy:/var/cache/ntfy
      - /etc/ntfy:/etc/ntfy
    networks:
      - proxy
    ports:
      - "127.0.0.1:3002:80"
    healthcheck: # optional: remember to adapt the host:port to your environment
      test:
        [
          "CMD-SHELL",
          "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  my-static-site:
    image: nginx:alpine
    container_name: my-static-site
    ports:
      - "127.0.0.1:3003:80"
    volumes:
      - /root/nginx/astro-site:/usr/share/nginx/html
    networks:
      - proxy

  privatebin:
    container_name: privatebin
    restart: always
    read_only: true
    user: 1000:1000
    image: privatebin/nginx-fpm-alpine:latest
    ports:
      - "127.0.0.1:3004:8080"
    volumes:
      - "./privatebin-data:/srv/data"
    networks:
      - proxy

networks:
  proxy:
    driver: bridge

volumes:
  uptime-kuma:
